var userName;
var myName = "Abdul Rehman";
var message = "Hello World";
alert(message);
var studentName = "Ali Khan";
var studentAge = "19 Years Old";
var studentInstitute = "SSUET";
var studentCourse = "Mobile & Cloud Computing - Module A";
var pizza1 = "PIZZA";
var pizza2 = "PIZZ";
var pizza3 = "PIZ";
var pizza4 = "PI";
var pizza5 = "P";
alert(studentName);
alert(studentAge);
alert(studentInstitute);
alert(studentCourse);
alert(pizza1+"\n"+pizza2+"\n"+pizza3+"\n"+pizza4+"\n"+pizza5);
var numberOfChildren = "2 Child";
var partnerName = "ABC";
var geographicLocation = "USA";
var jobTitle = "Software Developer";
alert("You will be a "+jobTitle+" in "+geographicLocation+" and married to "+partnerName+" with "+numberOfChildren);
var email = "abdulrehman1239091@gmail.com";
alert("My email address is "+email);
document.write("A Smarter Way To Learn Java Script.");
